version: '3.3'

services:
  casbin:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    ports:
      - ${SERVER_PORT}:8080
    volumes:
      - ./data/log:/app/log
    depends_on:
      - mysql
      - redis
    networks:
      - casbinNetwork      
  redis:
    restart: always
    image: redis:latest
    command: >
      --requirepass ${REDIS_PASSWORD}
    networks:
      - casbinNetwork      
  mysql:
    restart: always
    container_name: mysql8
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_DATABASE: sandbox
#      MYSQL_USER: sandbox_user
#      MYSQL_PASSWORD: passpass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./data/mysql/data:/var/lib/mysql
      - ./data/sqls:/docker-entrypoint-initdb.d
      # - ./data/mysql/my.cnf:/etc/my.cnf:ro
      # - ./data/log/mysql:/var/log/mysql
    networks:
      - casbinNetwork
networks:
  casbinNetwork:      